name: Unit tests

on:
  push:
    branches:
      - master
      - android-10
  pull_request:
    branches:
      - master
      - android-10

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
        ./gradlew test
