#!/bin/bash
LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
echo "VNC server started. The default password is the account password for $USER"
